version: '3.8'

services:
  gik-app:
    container_name: gik-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
